import "../../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "react-hot-toast";
import { TAB_LOGO } from "@/common/constants";
import BackOfficeGlobalWrappers from "@/common/components/BackOfficeWrappers/BackOfficeGlobalWrappers";
import TreasurerSidebar from "@/module/TreasurerModule/components/TreasurerSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `STMO`,
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={TAB_LOGO} />
      <body className={inter.className}>
        <BackOfficeGlobalWrappers>
          <Toaster />
          <TreasurerSidebar>{children}</TreasurerSidebar>
        </BackOfficeGlobalWrappers>
      </body>
    </html>
  );
}
