import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import QueryClientWrapper from "@/common/components/QueryClientWrapper";
import { Toaster } from "react-hot-toast";
import { TAB_LOGO } from "@/common/constants";
import GlobalWrappers from "@/common/components/Wrappers/GlobalWrappers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: `STMO`,
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={TAB_LOGO} />
      <body className={inter.className}>
        <div className="flex flex-col w-full">
          <GlobalWrappers>
            <QueryClientWrapper>
              <Toaster />
              {children}
              {/* <FooterUserPage/> */}
              <Toaster />
            </QueryClientWrapper>
          </GlobalWrappers>
        </div>
      </body>
    </html>
  );
}
